#!/bin/bash

show_help () {
/usr/bin/cat <<END_OF_SHOW_HELP
$0 -d <DESTDIR> -h <HOSTNAME> -k <KEYFILE> -s <SERVICES>

  -d  Directory on remote server where backup will be made
  -h  Hostname to connect to.
  -k  Location of key to use
  -s  Services to stop/start before/after backup
  -u  User to connect as
END_OF_SHOW_HELP
} 

[[ $EUID != 0 ]] && echo "Must have super user privileges." && exit 1

OPTIND=1

while getopts "d:h:k:s:u:" opt; do
  case "$opt" in
    d)    rdir=$OPTARG;;
    h)    host=$OPTARG;;
    k)    kfil=$OPTARG;;
    s)    svcs=$OPTARG;;
    u)    user=$OPTARG;;
    '?')  show_help >&2 && exit 1;;
  esac
done

shift $((OPTIND-1))

[ -z ${kfil} ] && sshc = "ssh" || sshc="ssh -i ${kfil}"
echo ${sshc}
echo "`eval ${sshc} ${user}@${host} 'ls ${rdir} -1r|head -1'`"  
ldir="`eval ${sshc} ${user}@${host} 'ls ${rdir} -1r|head -1'`"  
[ "$ldir" == "`date +%F`" ] && { [ -t 1 ] && { echo "Already backed up for today"; exit 1; } || exit 1; }
[[ "$ldir" != "" ]] && ldst="--link-dest=${rdir}/${ldir}"

xcld+="--exclude swapfile "
xcld+="--exclude .thumbnails "
xcld+="--exclude .cache "
xcld+="--exclude /var/cache/pacman "
xcld+="--exclude /srv/build/x86_64/paul "
xcld+="--exclude /srv/build/i686/paul "

[ -t 1 ] && rsop="${ldst} ${xcld} --progress -xaze" 
[ -t 1 ] || rsop="${ldst} ${xcld} -qxaze" 

for binds in `/usr/bin/cat /etc/fstab | /usr/bin/grep bind | /usr/bin/sed 's/\t/ /g' | /usr/bin/sed 's/  */ /g' | /usr/bin/cut -d\  -f2`; do
  [ -t 1 ] && echo Unbinding ${binds}...
  /usr/bin/umount ${binds}
done

[ "${svcs}" != "none" ] && { [ -t 1 ] && echo "Stopping ${svcs}..."; } && /usr/bin/systemctl stop ${svcs}

[ -t 1 ] && echo "Rsyncing to ${user}@${host}..."
/usr/bin/rsync ${rsop} "${sshc}" / ${user}@${host}:${rdir}/`date +%F`

[ "${svcs}" != "none" ] && { [ -t 1 ] && echo "Restarting ${svcs}..."; } && /usr/bin/systemctl start ${svcs}

[ -t 1 ] && echo "Rebinding mounts..."
/usr/bin/mount -a

exit 0
