#!/bin/bash
if [ `which gcc 2> /dev/null` ]; then
  if [ "$( echo -e "4.9\n$(gcc --version | grep gcc | cut -d\  -f3)" | sort -V | head -n 1 )" == "4.9" ]; then
    CKINFO="$(gcc -c -Q -march=native --help=target | grep 'march=\|mtune=' | sed ':a;N;$!ba;s/\t/ /g;s/  *//g;s/-m/m/g;s/\n/ /g')"
    echo -n "${CKINFO}: "
    GMARCH=${CKINFO% *=*}
    GMARCH=${GMARCH#*=}
    case ${GMARCH} in
      bonnell)                  echo -n ck-atom ;;
      silvermont)               echo -n ck-silvermont ;;
      core2)                    echo -n ck-core2 ;;
      nahelem)                  echo -n ck-nehalem ;;
      sandybridge)              echo -n ck-sandybridge ;;
      ivybridge)                echo -n ck-ivybridge ;;
      haswell)		        echo -n ck-haswell ;;
      broadwell)                echo -n ck-broadwell ;;
      pentium4|prescott|nocona) echo -n ck-p4 ;;
      pentm|pentium-m)          echo -n ck-pentm ;;

      athlon|athlon-4|athlon-tbird|athlon-mp|athlon-xp|k8-sse3)	echo -n ck-kx ;;
      amdfam10) echo -n ck-k10 ;;
      btver1)   echo -n ck-bobcat ;;
      bdver1)   echo -n ck-bulldozer ;;
      bdver2)   echo -n ck-piledriver ;;
    
      *)    echo -n ck-generic ;;
    esac
    echo -n ' recommended, '
  else
    echo "GCC version >=4.9 required."
  fi
else
  echo "GCC is not installed."
fi

CKINST="no ck package $(pacman -Qqs linux-ck | sed 's/ck$/ck-generic/g' | grep -v 'broadcom\|headers\|nvidia\|virtualbox') installed."
CKINST="${CKINST/no ck package linux/linux}"
CKINST="${CKINST/linux-/}"
echo $CKINST >&2
