#!/bin/bash
user="${1}"
pswd="${2}"
bdir="/srv/backup/mysql"

rm ${bdir}/*.sql

/usr/bin/mysqldump -u${user} -p${pswd} --all-databases > ${bdir}/ALL-ALL.sql
/usr/bin/mysqldump -td -u${user} -p${pswd} --all-databases > ${bdir}/ALL-DTBS.sql

dcmd="/usr/bin/mysql -u${user} -p${pswd} -sre 'show databases;' |
  egrep -vi 'information_schema|performance_schema'"
for dtbs in `eval ${dcmd}`; do
  tcmd="/usr/bin/mysql -u${user} -p${pswd} ${dtbs} -sre 'show tables;'"
  for tabl in `eval ${tcmd}`; do
    echo ${dtbs}.${tabl}
    /usr/bin/mysqldump --skip-extended-insert -u${user} -p${pswd} ${dtbs} ${tabl} > ${bdir}/${dtbs}.${tabl}.sql
  done
done

#exit 0

cd ${bdir}
/usr/bin/git add -A *.sql
/usr/bin/git commit -am "Backup For `date +%Y-%m-%d_%H:%M:%S`"
/usr/bin/git push -u origin master
