#!/bin/bash
cat /etc/ssh/sshd_config | grep 'PasswordAuthentication yes' > /dev/null
[[ $? -eq 0 ]] && { from=yes; to=no; } || { from=no; to=yes; }

for OPTION in PasswordAuthentication ChallengeResponseAuthentication; do
  echo ${OPTION} $from =\> $to
  sudo sed -i "s/${OPTION} ${from}/${OPTION} ${to}/g" /etc/ssh/sshd_config
done
sudo systemctl restart sshd
