#!/bin/bash
cat /etc/ssh/sshd_config | grep 'PasswordAuthentication yes' > /dev/null
[[ $? -eq 0 ]] && { from=yes; to=no; } || { from=no; to=yes; }
echo PasswordAuthentication $from =\> $to
sudo sed -i "s/PasswordAuthentication ${from}/PasswordAuthentication ${to}/g" /etc/ssh/sshd_config
sudo sed -i "s/ChallengeResponseAuthentication ${from}/ChallengeResponseAuthentication ${to}/g" /etc/ssh/sshd_config
sudo systemctl restart sshd
