#!/bin/bash
# This script automates system updates in Arch Linux

# Determine country of origin
echo "$(tput setaf 12)::$(tput sgr0) Determine country of origin..."
GIPURL="http://api.petabyet.com/geoip"
GETVAL=".country_code"
MY_COO="$(/usr/bin/curl -s ${GIPURL} | /usr/bin/jq -r ${GETVAL})"
echo "$(tput setaf 10)==>$(tput sgr0) ${MY_COO}"

# Call the update-reflector script to get the best mirrors
echo "$(tput setaf 12)::$(tput sgr0) Determine best mirrors..."
/usr/bin/sudo /usr/bin/reflector -p https -l 5 -c "${MY_COO}" --sort rate --save /etc/pacman.d/mirrorlist
tail -5 /etc/pacman.d/mirrorlist | sed "s/^Server = \(.*\)/$(tput setaf 10)==>$(tput sgr0) \1/g"

# Build command to execute
cmd="/usr/bin/sudo /usr/bin/pacman -Syu --noconfirm"

# If local shared cache exists, use it
[[ -d /mnt/nfs/pacman/pkg ]] && cmd+=" --cachedir /mnt/nfs/pacman/pkg"

# Execute command
eval "$cmd"

if [ ${?} != 0 ]; then
  echo ":: Pacman failed."
else
  if tty -s; then
    if type pacaur &> /dev/null; then
      if [ ! -d /pacaur ]; then
        sudo mkdir -p /pacaur
        sudo chmod 1777 /pacaur
        if [ ! -d /pacaur/${USER} ]; then
          mkdir /pacaur/${USER}
        fi
      fi
    AURDEST=/pacaur/${USER} /usr/bin/pacaur -u --devel --noedit --needed --noconfirm
    fi
  fi
fi

# Adds apt-like warning of packages no longer needed if TTY
if tty -s; then
 echo -n "Checking for orphaned packages..."
 orphed="$(pacman -Qtdq | sed ':a;N;$!ba;s/\n/ /g')"; echo "done"
 if [ -n "${orphed}" ]; then
  echo -e '\e[1;34m:: \e[1;37mThe following packages are no longer required.  '
  #echo -e  'Use \e[1;33mpacman -Rs $(pacman -Qtdq)\e[1;37m to remove them.\e[0m'
  echo "${orphed}"
  read -n 1 -t 300 -p "Remove orphans now? [y/N] " RMORPH
  echo ""
  case ${RMORPH} in
   y|Y) /usr/bin/sudo /usr/bin/pacman --noconfirm -Rs $(/usr/bin/pacman -Qtdq) ;;
   n|N) echo "Not removing orphans at this time." ;;
   *) echo "5-minute timeout reached.  Not removing orphans." ;;
  esac
 fi
fi

# Check /usr/bin/init
if [ -e /usr/bin/init-kexec ]; then
  /usr/bin/sudo /usr/bin/diff -qs /usr/bin/init /usr/bin/init-kexec
  if [ $? != 0 ]; then
    /usr/bin/sudo /usr/bin/rm /usr/bin/init
    /usr/bin/sudo /usr/bin/cp /usr/bin/init-kexec /usr/bin/init
    echo "Replaced /usr/bin/init"
  fi
fi
