#!/usr/bin/env sh

function need_sudo() {
while true; do
  sudo echo 'test' > /dev/null
  [ "${?}" -eq "0" ] && SUDO=sudo && break
done
}

[ -e "${HOME}/.nanorc" ] && { TARGET="${HOME}/.nanorc"; } || { TARGET="/etc/nanorc"; need_sudo; }
echo "Patching ${TARGET}"
diff -u "${TARGET}" <(echo -e "$(grep -v '^include' "${TARGET}")\n\n$(cat /usr/share/nano-syntax-highlighting/nanorc.sample)") | tee /dev/tty | ${SUDO} patch --verbose "${TARGET}"
